version: '3'
services:
  redis:
    image: "redis:alpine"
    environment:
      POSTGRES_PASSWORD: airbnbReviews
      POSTGRES_USER: postgres
    networks:
      - redis
  reviews:
    build: .
    depends_on:
      - redis
    ports:
      - '3002:3002'
    networks:
      - redis
    command: ["npm", "start"]
networks:
  redis:
    driver: bridge